#Name: Ramin
#Date: 04/11/24
#Title: Wheels On The Bus
#Purpose: Sing wheels on the bus.

print(f'The Wheel On The Bus')
print(f'The wheels on the bus go round and round')
print(f'Round and round')
print(f'Round and round')
print(f'The wheels on the bus go round and round')
print(f'All through the town')
print(f'The wipers on the bus go Swish, swish, swish')
print(f'Swish, swish, swish')
print(f'Swish, swish, swish')
print(f'The wipers on the bus go Swish, swish, swish')
print(f'All through the town')
print(f'The horn on the bus goes Beep, beep, beep')
print(f'Beep, beep, beep')
print(f'Beep, beep, beep')
print(f'The horn on the bus goes Beep, beep, beep')
print(f'All through the town')
print(f'The doors on the bus go open and shut')
print(f'Open and shut')
print(f'Open and shut')
print(f'The doors on the bus go open and shut')
print(f'All through the town')
print(f'The Driver on the bus says Move on back')
print(f'Move on back, move on back')
print(f'The Driver on the bus says Move on back')
print(f'All through the town')
print(f'The babies on the bus says Wah, wah, wah')
print(f'Wah, wah, wah')
print(f'Wah, wah, wah')
print(f'The babies on the bus says Wah, wah, wah')
print(f'All through the town')
print(f'The mommies on the bus says Shush, shush, shush')
print(f'Shush, shush, shush')
print(f'Shush, shush, shush')
print(f'The mommies on the bus says Shush, shush, shush ')
print(f'All through the town')
print(f'The turbo on the bus goes Vwoosh Vwoosh Vwoosh, Vwoosh Vwoosh Vwoosh, Vwoosh Vwoosh Vwoosh')
print(f'The turbo on the bus goes Vwoosh Vwoosh Vwoosh, all through the town')
print(f'The cat on the bus goes meow meow meow, meow meow meow, meow meow meow')
print(f'the cat on the bus goes meow meow meow, all through the town')
print(f'the Mansiv on the bus goes yap yap yap, yap yap yap, yap yap yap')
print(f'The Mansiv on the bus goes yap yap yap, all through the town')