print(f'The Wheel On The Bus')
print(f'The wheels on the bus go round and round')
print(f'Round and round')
print(f'Round and round')
print(f'The wheels on the bus go round and round')
print(f'All through the town')
print(f'The wipers on the bus go Swish, swish, swish')
print(f'Swish, swish, swish')
print(f'Swish, swish, swish')
print(f'The wipers on the bus go Swish, swish, swish')
print(f'All through the town')
print(f'The horn on the bus goes Beep, beep, beep')
print(f'Beep, beep, beep')
print(f'Beep, beep, beep')
print(f'The horn on the bus goes Beep, beep, beep')
print(f'All through the town')
print(f'The doors on the bus go open and shut')
print(f'Open and shut')
print(f'Open and shut')
print(f'The doors on the bus go open and shut')
print(f'All through the town')
print(f'The Driver on the bus says Move on back')
print(f'Move on back, move on back')
print(f'The Driver on the bus says Move on back')
print(f'All through the town')
print(f'The babies on the bus says Wah, wah, wah')
print(f'Wah, wah, wah')
print(f'Wah, wah, wah')
print(f'The babies on the bus says Wah, wah, wah')
print(f'All through the town')
print(f'The mommies on the bus says Shush, shush, shush')
print(f'Shush, shush, shush')
print(f'Shush, shush, shush')
print(f'The mommies on the bus says Shush, shush, shush ')
print(f'All through the town')
print(f'...')
print(f'...')
print(f'...')
print(f'...')
print(f'...')
print(f'...')